package com.lizziputt.consoleapp;

public enum ExecutionStrategy {
    CLASSROOM_FIND_ALL("CLASSROOM_FIND_ALL"),
    CLASSROOM_FIND_BY_ID("CLASSROOM_FIND_BY_ID"),
    CLASSROOM_CREATE("CLASSROOM_CREATE"),
    CLASSROOM_UPDATE("CLASSROOM_UPDATE"),
    CLASSROOM_REMOVE("CLASSROOM_REMOVE"),

    STUDENT_FIND_ALL("STUDENT_FIND_ALL"),
    STUDENT_FIND_BY_ID("STUDENT_FIND_BY_ID"),
    STUDENT_CREATE("STUDENT_CREATE"),
    STUDENT_UPDATE("STUDENT_UPDATE"),
    STUDENT_REMOVE("STUDENT_REMOVE"),

    SUBJECT_FIND_ALL("SUBJECT_FIND_ALL"),
    SUBJECT_FIND_BY_ID("SUBJECT_FIND_BY_ID"),
    SUBJECT_CREATE("SUBJECT_CREATE"),
    SUBJECT_UPDATE("SUBJECT_UPDATE"),
    SUBJECT_REMOVE("SUBJECT_REMOVE"),

    TEACHER_FIND_ALL("TEACHER_FIND_ALL"),
    TEACHER_FIND_BY_ID("TEACHER_FIND_BY_ID"),
    TEACHER_CREATE("TEACHER_CREATE"),
    TEACHER_UPDATE("TEACHER_UPDATE"),
    TEACHER_REMOVE("TEACHER_REMOVE"),

    TIMETABLE_FIND_ALL("TIMETABLE_FIND_ALL"),
    TIMETABLE_FIND_BY_ID("TIMETABLE_FIND_BY_ID"),
    TIMETABLE_CREATE("TIMETABLE_CREATE"),
    TIMETABLE_UPDATE("TIMETABLE_UPDATE"),
    TIMETABLE_REMOVE("TIMETABLE_REMOVE"),

    RETURN("RETURN");

    private final String name;

    ExecutionStrategy(String name) {this.name = name;}

    public String getName() {
        return name;
    }
}
